### PR TITLE
1.9.2 - Email and SQL Validation

### LINKED ISSUE #56: Two Factor Authentication
- [x] 1. Have an option for a user to enable two-factor authentication. 
- [x] 2. The pin should be sent to the user's email address and be added to the Login stats.
- [x] 3. This should have an enable/disable option.
- [x] 4. This should stop the login if the pin is incorrect.
- [x] 5. If the email is invalid, then it should catch this and not give the option to the user.

### PR DESCRIPTION
**Pull request by Jody-Whitis**
Adding email validation on creation and editing.
Adding sql validation on string-related parameters.
Fix for logging missing functions on password reminder and two-factor pin.

### CODE REVIEW

**Comment by Jody-Whitis** [comment]
**_Test Cases for 1.9.2 Merge:_**

- [x] 1. Creating an email triggers validation and prompt to the user.
- [x] 2. Editing an email triggers validation and prompt to the user.
- [x] 3. SQL validation occurs on inserting queries on strings.
- [x] 4. SQL validation occurs on selecting queries on strings.
- [x] 5. SQL validation occurs on deleting queries on strings.
- [x] 6. SQL validation occurs on updating queries on strings.

File: Pool/Register.vb [hunk 1]
```diff
@@ -119,7 +119,13 @@ Public Class Register
     Private Sub btnConfirm_Click(sender As Object, e As EventArgs) Handles btnConfirm.Click
         Dim registerSQL As New StringBuilder
         If ValidateRegister(New TextBox() {txtUseremail, txtPassword, TxtPasswordConfirm, TxtPasswordConfirm}).Equals(True) Then
-            user.userEmail = txtUseremail.Text
+            If inputValidation.isValid(txtUseremail.Text) Then
+                user.userEmail = txtUseremail.Text
+            Else
+                Dim RequiredField As DialogResult = MessageBox.Show($"Missing required fields",
+                      "Missing Requirement", MessageBoxButtons.OK, MessageBoxIcon.Hand)
+                Exit Sub
```
Comment (Jody-Whitis) [inline Pool/Register.vb]: Pushing a fix for this message

**Comment by Jody-Whitis** [comment]
> **_Test Cases for 1.9.2 Merge:_**
> 
> * [x]  1. Creating an email triggers validation and prompt to the user.
> * [x]  2. Editing an email triggers validation and prompt to the user.
> * [x]  3. SQL validation occurs on inserting queries on strings.
> * [x]  4. SQL validation occurs on selecting queries on strings.
> * [x]  5. SQL validation occurs on deleting queries on strings.
> * [x]  6. SQL validation occurs on updating queries on strings.
--------------------------------------------------------------------------------
Test cases for this change pass. Merging 1.9.2 to master.
